before_script:
    - . /home/gitlab-runner/setup-paths.sh 
    - export OPENRAM_HOME="`pwd`/compiler"
    - export OPENRAM_TECH="`pwd`/technology:/home/PDKs/skywater-tech"

stages:
  - test
  - coverage
    
freepdk45:
  stage: test
  script: 
    - coverage run -p $OPENRAM_HOME/tests/regress.py -j 16 -t freepdk45
  artifacts:
    paths:
      - .coverage.*
    expire_in: 1 week

scn4m_subm:
  stage: test
  script: 
    - coverage run -p $OPENRAM_HOME/tests/regress.py -j 16 -t scn4m_subm
  artifacts:
    paths:
      - .coverage.*
    expire_in: 1 week

# s8:
#   stage: test
#   script: 
#     - coverage run -p $OPENRAM_HOME/tests/regress.py -t s8
#   artifacts:
#     paths:
#       - .coverage.*
#     expire_in: 1 week

coverage:
  stage: coverage
  script:
    - coverage combine
    - coverage report
    - coverage html -d coverage_html
  artifacts:
    paths:
      - coverage_html
    expire_in: 1 week
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

