name: ci
on: [push]
  coverage_cleanup:
    if: ${{ always() }}
    runs-on: self-hosted
    steps:
      - name: Coverage cleanup
        run: |
         python3-coverage erase
jobs:
  scn4me_subm:
    needs: [coverage_cleaup]
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: SCMOS test
        run: |
         . /home/github-runner/setup-paths.sh 
         export OPENRAM_HOME="`pwd`/compiler"
         export OPENRAM_TECH="`pwd`/technology:/software/PDKs/skywater-tech"
         export OPENRAM_TMP="${{ github.workspace }}/scn4me_subm"
	 rm -rf $OPENRAM_TMP
         python3-coverage run -p $OPENRAM_HOME/tests/regress.py -j 20 -t scn4m_subm
      - name: Archive
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
         name: scn4me_subm Archives
         path: ${{ github.workspace }}/scn4me_subm/*/
  freepdk45:
    needs: [coverage_cleaup]  
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: FreePDK45 test
        run: |
         . /home/github-runner/setup-paths.sh 
         export OPENRAM_HOME="`pwd`/compiler"
         export OPENRAM_TECH="`pwd`/technology:/software/PDKs/skywater-tech"
         export OPENRAM_TMP="${{ github.workspace }}/freepdk45"
	 rm -rf $OPENRAM_TMP
         python3-coverage run -p $OPENRAM_HOME/tests/regress.py -j 20 -t freepdk45
      - name: Archive
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
         name: FreePDK45 Archives
         path: ${{ github.workspace }}/freepdk45/*/
  coverage_stats:
    if: ${{ always() }}
    needs: [scn4me_subm, freepdk45]
    runs-on: self-hosted
    steps:
      - name: Coverage stats
        run: |
         python3-coverage combine
         python3-coverage report
         python3-coverage html -d ${{ github.workspace }}/coverage_html
      - name: Archive coverage
        uses: actions/upload-artifact@v2
        with:
         name: code-coverage-report
         path: ${{ github.workspace }}/coverage_html/
      - name: Cleanup
        run: |
         python3-coverage erase

