name: deploy
on:
  push:
    branches:
      - stable
jobs:
  deploy_pip:
  if: ${{ startsWith(github.event.head_commit.message, 'Bump version:') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
         python3 -m pip install virtualenv
      - name: Build Python package
        run: |
         make build_library
      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
