name: sync
on:
  workflow_call:
    secrets:
      WORKFLOW_ACCESS_TOKEN:
        required: true
jobs:
  sync_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
      - name: Synchronize OpenRAM repo
        run: |
         # Configure pusher account
         git config --global user.name "mrg"
         git config --global user.email "mrg@ucsc.edu"
         # Add remote repo
         git remote add public-repo https://${{ secrets.WORKFLOW_ACCESS_TOKEN }}@github.com/VLSIDA/OpenRAM.git
         git pull public-repo dev
         # Push the latest changes
         git push -u public-repo HEAD:dev
